/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Window;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author danio
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        setLocationRelativeTo(null);
        //botonLogin.setBackground(new Color(0, 0, 0, 0));
        //textoUsuario.setBackground(new Color(0, 0, 0, 0));
        //textoContraseña.setBackground(new Color(0, 0, 0, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        etiquetaIcon = new javax.swing.JLabel();
        botonExit = new javax.swing.JButton();
        botonLogin = new javax.swing.JButton();
        textoContraseña = new javax.swing.JPasswordField();
        textoUsuario = new javax.swing.JTextField();
        etiquetaFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/iconNave.png"))); // NOI18N
        panel.add(etiquetaIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 200, 200));

        botonExit.setBackground(new java.awt.Color(102, 102, 102));
        botonExit.setForeground(new java.awt.Color(255, 255, 255));
        botonExit.setText("Salir");
        botonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonExitActionPerformed(evt);
            }
        });
        panel.add(botonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        botonLogin.setBackground(new java.awt.Color(102, 102, 102));
        botonLogin.setForeground(new java.awt.Color(255, 255, 255));
        botonLogin.setText("Iniciar Sesión");
        botonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLoginActionPerformed(evt);
            }
        });
        panel.add(botonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, -1));

        textoContraseña.setBackground(new java.awt.Color(0, 0, 0));
        textoContraseña.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textoContraseña.setForeground(new java.awt.Color(255, 255, 255));
        textoContraseña.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contraseña", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12), new java.awt.Color(0, 255, 255))); // NOI18N
        textoContraseña.setOpaque(true);
        textoContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoContraseñaActionPerformed(evt);
            }
        });
        panel.add(textoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 220, 60));

        textoUsuario.setBackground(new java.awt.Color(0, 0, 0));
        textoUsuario.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        textoUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuario", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12), new java.awt.Color(0, 255, 255))); // NOI18N
        textoUsuario.setOpaque(true);
        textoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoUsuarioActionPerformed(evt);
            }
        });
        panel.add(textoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 220, 60));

        etiquetaFondo.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaFondo.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/FondoNebulosa.jpg"))); // NOI18N
        panel.add(etiquetaFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoContraseñaActionPerformed
        setVisible(true);
        
    }//GEN-LAST:event_textoContraseñaActionPerformed

    private void textoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoUsuarioActionPerformed
        
    }//GEN-LAST:event_textoUsuarioActionPerformed

    private void botonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonExitActionPerformed

    private void botonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLoginActionPerformed
        String usuario = "programador1";
        String contraseña = "java";
        
        String password = new String(textoContraseña.getPassword());
        
        if (textoUsuario.getText().isEmpty() || textoContraseña.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Algun campo se encuentra vacío");
        } else if (textoUsuario.getText().equals(usuario) && password.equals(contraseña)) {
            JOptionPane.showMessageDialog(null, """
                                                El usuario y contrase\u00f1a es correcto
                                                BIENVENIDO!""");
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "ERROR! Usuario desconocido");
        }
    }//GEN-LAST:event_botonLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonExit;
    private javax.swing.JButton botonLogin;
    private javax.swing.JLabel etiquetaFondo;
    private javax.swing.JLabel etiquetaIcon;
    private javax.swing.JPanel panel;
    private javax.swing.JPasswordField textoContraseña;
    private javax.swing.JTextField textoUsuario;
    // End of variables declaration//GEN-END:variables
}
