
package Ventana;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Daniel Valencia 2022
 */
public class Ventana extends javax.swing.JFrame {
    private Timer tiempo;
    private  int centesimaSegundo = 0, segundos = 0, minutos = 0, horas = 0;
    
    private ActionListener acciones = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            centesimaSegundo++;
            if (centesimaSegundo == 100) {
                segundos++;
                centesimaSegundo = 0;
            }
            if (segundos == 60) {
                minutos++;
                segundos = 0;
            }
            if (minutos == 60) {
                horas++;
                minutos = 0;
            }
            actualizarEtiquetaTiempo();
        }
    };
    
    private void actualizarEtiquetaTiempo(){
        String texto = (horas<=9 ? "0":"") + horas + ":" + (minutos<=9 ? "0":"") + minutos + ":" + (segundos<=9 ? "0":"") + segundos + ":" + (centesimaSegundo<=9 ? "0":"") + centesimaSegundo;
        etiquetaTiempo.setText(texto);
    }
    
    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
        tiempo = new Timer(10, acciones);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        imagenCronometro = new javax.swing.JLabel();
        etiquetaCronometro = new javax.swing.JLabel();
        etiquetaTiempo = new javax.swing.JLabel();
        botonIniciar = new javax.swing.JButton();
        botonPausar = new javax.swing.JButton();
        botonDetener = new javax.swing.JButton();
        etiquetaJuego = new javax.swing.JLabel();
        etiquetaFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cronómetro");
        setResizable(false);

        panel.setMinimumSize(new java.awt.Dimension(550, 309));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagenCronometro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/crono.png"))); // NOI18N
        panel.add(imagenCronometro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 103, 100));

        etiquetaCronometro.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        etiquetaCronometro.setForeground(new java.awt.Color(255, 255, 0));
        etiquetaCronometro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaCronometro.setText("Cronómetro");
        etiquetaCronometro.setPreferredSize(new java.awt.Dimension(178, 45));
        panel.add(etiquetaCronometro, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, 40));

        etiquetaTiempo.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        etiquetaTiempo.setForeground(new java.awt.Color(255, 0, 0));
        etiquetaTiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTiempo.setText("00:00:00:00");
        panel.add(etiquetaTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 150, 30));

        botonIniciar.setBackground(new java.awt.Color(153, 153, 153));
        botonIniciar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        botonIniciar.setText("Iniciar");
        botonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarActionPerformed(evt);
            }
        });
        panel.add(botonIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 90, -1));

        botonPausar.setBackground(new java.awt.Color(153, 153, 153));
        botonPausar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        botonPausar.setText("Pausar");
        botonPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPausarActionPerformed(evt);
            }
        });
        panel.add(botonPausar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 90, -1));

        botonDetener.setBackground(new java.awt.Color(153, 153, 153));
        botonDetener.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        botonDetener.setText("Detener");
        botonDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDetenerActionPerformed(evt);
            }
        });
        panel.add(botonDetener, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 90, -1));

        etiquetaJuego.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaJuego.setText("(Que comience el juego)");
        panel.add(etiquetaJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        etiquetaFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/saw.jpg"))); // NOI18N
        panel.add(etiquetaFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPausarActionPerformed
        tiempo.stop();
        botonIniciar.setEnabled(true);
        botonPausar.setEnabled(false);
    }//GEN-LAST:event_botonPausarActionPerformed

    private void botonDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDetenerActionPerformed
        if (tiempo.isRunning()) {
            tiempo.stop();
            botonIniciar.setEnabled(true);
        }
        botonIniciar.setText("Iniciar");
        botonPausar.setEnabled(false);
        botonDetener.setEnabled(false);
        
        horas = 0;
        minutos = 0;
        segundos = 0;
        centesimaSegundo = 0; 
          
        actualizarEtiquetaTiempo();
        
        etiquetaJuego.setText("(Que comience el juego)");
    }//GEN-LAST:event_botonDetenerActionPerformed

    private void botonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarActionPerformed
        tiempo.start();
        botonIniciar.setEnabled(false);
        botonIniciar.setText("Reanudar");
        botonPausar.setEnabled(true);
        botonDetener.setEnabled(true);
        
        etiquetaJuego.setText(null);
    }//GEN-LAST:event_botonIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDetener;
    private javax.swing.JButton botonIniciar;
    private javax.swing.JButton botonPausar;
    private javax.swing.JLabel etiquetaCronometro;
    private javax.swing.JLabel etiquetaFondo;
    private javax.swing.JLabel etiquetaJuego;
    private javax.swing.JLabel etiquetaTiempo;
    private javax.swing.JLabel imagenCronometro;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
